### PR TITLE
Jules ginger patch 1

### PR DESCRIPTION
**Pull request by christinna9031**

### CODE REVIEW

**Review by christinna9031 — COMMENTED** [review]
@JulesGinger 
These are not necessary to add anymore, the extension automatically converts everything to base lowercase characters, so we should be only adding those. 

B̟est viewers at
B̟est viewers on

**Comment by JulesGinger** [comment]
Ah those are because of the little dot below the b, which might pass through? Don't know if SAMMI would recognize both instances.

**Comment by christinna9031** [comment]
Yup, it passes them :)

**Comment by christinna9031** [comment]
I manually committed it. Closing now :)

**Pull request closed without merging**
